version: "3.9"

services:
  django:
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    build:
      context: ../../
      dockerfile: Docker/Dev/Dockerfile
    command: >
        bash -c "cd src
        && python3 manage.py makemigrations account
        && python3 manage.py makemigrations series
        && python3 manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ../../src:/code/src