version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ../../config/db/databasepostgresql_env

  django:
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    build:
      context: ../../
      dockerfile: Docker/Dev/Dockerfile
    command: >
        bash -c "cd src
        && python3 manage.py makemigrations account
        && python3 manage.py makemigrations series
        && python3 manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ../../src:/code/src
    depends_on:
      - db

volumes:
  dbdata: