version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - static_volume:/src/django_static
    env_file:
      - config/db/databasepostgresql_env

  django:
    build: .
    command: gunicorn src.config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "1337:8080"
    volumes:
      - ./config/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/src/django_static
    depends_on:
      - django

volumes:
  dbdata:
  static_volume: