version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - config/db/databasepostgresql_env

  django:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    build: .
    command: python3 src/manage.py runserver 0.0.0.0:8000 --settings=config.settings.production
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/django_static

  nginx:
    image: nginx
    ports:
      - "1337:8080"
    volumes:
      - ./config/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/django_static
    depends_on:
      - django

volumes:
  dbdata:
  static_volume: