version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ../../config/db/databasepostgresql_env

  rabbitmq:
    image: rabbitmq

  django:
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    build:
      context: ../../
      dockerfile: Docker/Prod/Dockerfile
    command: >
        bash -c "cd src
        && python3 manage.py makemigrations
        && echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ makemigrations completed ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
        && python3 manage.py migrate
        && echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ migrate completed ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
        && python3 manage.py collectstatic --noinput
        && echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ collectstatic completed ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
        && gunicorn --bind 0.0.0.0:8000 --timeout 60 config.wsgi"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    volumes:
      - static_volume:/django_static

  celery-worker:
    restart: always
    build:
      context: ../../
      dockerfile: Docker/Prod/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    command: >
        bash -c "cd src
        && celery -A config worker -l info -f worker.log"
    depends_on:
      - django

  celery-beat:
    restart: always
    build:
      context: ../../
      dockerfile: Docker/Prod/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    command: >
        bash -c "cd src
        && celery -A config beat -l info -f beat.log"
    depends_on:
      - celery-worker

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../../config/nginx/server-cloudflare.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/django_static
    depends_on:
      - django

#TODO: add volume for celery logs
volumes:
  dbdata:
  static_volume:
